name: SwiftSyft CI

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=14.0,name=iPhone 11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Force Xcode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app  
      - name: Install Dependencies
        run: |
          cd Example
          pod repo update
          pod install
          gem install slather
        shell: bash    
      - name: Build SwiftSyft project - ${{ matrix.destination }}
        run: | 
          set -o pipefail && env NSUnbufferedIO=YES xcodebuild test -scheme SwiftSyft-Example -workspace SwiftSyft.xcworkspace -destination "${{ matrix.destination }}" CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=13.0 | xcpretty
          slather
          bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml

